In [4]:
def convert_units(value, conversion_type):
    """
    Converts a value between different units of measurement.

    Parameters:
        value (float): The number to convert
        conversion_type (str): The type of conversion to perform

    Returns:
        float: The converted value, or None if invalid
    """

    if conversion_type == "1":   # meters to feet
        return value * 3.28084

    elif conversion_type == "2": # feet to meters
        return value / 3.28084

    elif conversion_type == "3": # kg to pounds
        return value * 2.20462

    elif conversion_type == "4": # pounds to kg
        return value / 2.20462

    elif conversion_type == "5": # liters to gallons
        return value * 0.264172

    elif conversion_type == "6": # gallons to liters
        return value / 0.264172

    else:
        return None  # invalid option


def main():
    """Main function that runs the unit converter program."""

    print("===== Unit Converter =====")
    print("Choose a conversion:")
    print("1. Meters → Feet")
    print("2. Feet → Meters")
    print("3. Kilograms → Pounds")
    print("4. Pounds → Kilograms")
    print("5. Liters → Gallons")
    print("6. Gallons → Liters")

    choice = input("Enter your choice (1-6): ")

    try:
        value = float(input("Enter the value to convert: "))

        result = convert_units(value, choice)

        if result is None:
            print("Invalid choice. Please enter a number between 1 and 6.")
        else:
            print(f"Result: {result:.4f}")

    except ValueError:
        print("Invalid input! Please enter a numeric value.")


# Run the program
main()

===== Unit Converter =====
Choose a conversion:
1. Meters → Feet
2. Feet → Meters
3. Kilograms → Pounds
4. Pounds → Kilograms
5. Liters → Gallons
6. Gallons → Liters
Enter your choice (1-6): 3
Enter the value to convert: 5
Result: 11.0231


In [6]:
def calculate_sum(numbers):
    """
    Returns the sum of a list of numbers.

    Parameters:
        numbers (list): A list of numeric values

    Returns:
        float: The sum of all numbers in the list
    """
    total = 0
    for n in numbers:
        total += n
    return total


def calculate_average(numbers):
    """
    Returns the average of a list of numbers.

    Parameters:
        numbers (list): A list of numeric values

    Returns:
        float: The average of all numbers in the list
    """
    return calculate_sum(numbers) / len(numbers)


def calculate_maximum(numbers):
    """
    Returns the maximum value in a list of numbers.

    Parameters:
        numbers (list): A list of numeric values

    Returns:
        float: The largest number in the list
    """
    biggest = numbers[0]
    for n in numbers:
        if n > biggest:
            biggest = n
    return biggest


def calculate_minimum(numbers):
    """
    Returns the minimum value in a list of numbers.

    Parameters:
        numbers (list): A list of numeric values

    Returns:
        float: The smallest number in the list
    """
    smallest = numbers[0]
    for n in numbers:
        if n < smallest:
            smallest = n
    return smallest


def main():
    """Main function that runs the math operations program."""

    print("===== Math Operations =====")
    print("Choose an operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    choice = input("Enter your choice (1-4): ")

    try:
        raw = input("Enter numbers separated by spaces (e.g. 1 2 3 4): ")
        numbers = [float(x) for x in raw.split()]

        if len(numbers) == 0:
            print("Error: You entered an empty list!")

        elif choice == "1":
            print(f"Sum = {calculate_sum(numbers)}")

        elif choice == "2":
            print(f"Average = {calculate_average(numbers)}")

        elif choice == "3":
            print(f"Maximum = {calculate_maximum(numbers)}")

        elif choice == "4":
            print(f"Minimum = {calculate_minimum(numbers)}")

        else:
            print("Invalid choice! Please enter 1, 2, 3 or 4.")

    except ValueError:
        print("Invalid input! Please enter numeric values only.")


main()

===== Math Operations =====
Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice (1-4): 3
Enter numbers separated by spaces (e.g. 1 2 3 4): 4 6 8 3
Maximum = 8.0


In [8]:
# SECTION: List Manipulation (Q.1 to Q.7)
# Q.1 - List Manipulation - Extract Every Other Element
# Takes a list and returns elements at positions 0, 2, 4...
def extract_every_other(lst):
    """
    Extracts every other element starting from the first.

    Parameters:
        lst (list): Input list

    Returns:
        list: Every other element from the original list
    """
    return lst[::2]

print("Q.1:", extract_every_other([1, 2, 3, 4, 5, 6]))

Q.1: [1, 3, 5]


In [9]:
# Q.2 - List Manipulation - Slice a Sublist
# Returns elements from start index to end index (inclusive)
def get_sublist(lst, start, end):
    """
    Returns a sublist from start to end index (inclusive).

    Parameters:
        lst (list): Input list
        start (int): Starting index
        end (int): Ending index (inclusive)

    Returns:
        list: Sublist from start to end
    """
    return lst[start:end+1]

print("Q.2:", get_sublist([1, 2, 3, 4, 5, 6], 2, 4))

Q.2: [3, 4, 5]


In [10]:
# Q.3 - List Manipulation - Reverse a List Using Slicing
# Uses slicing trick [::-1] to reverse the list
def reverse_list(lst):
    """
    Reverses a list using slicing.

    Parameters:
        lst (list): Input list

    Returns:
        list: Reversed version of the input list
    """
    return lst[::-1]

print("Q.3:", reverse_list([1, 2, 3, 4, 5]))

Q.3: [5, 4, 3, 2, 1]


In [11]:
# Q.4 - List Manipulation - Remove First and Last Elements
# Slices from index 1 to second-to-last element
def remove_first_last(lst):
    """
    Removes the first and last elements of a list.

    Parameters:
        lst (list): Input list

    Returns:
        list: List without first and last elements
    """
    return lst[1:-1]

print("Q.4:", remove_first_last([1, 2, 3, 4, 5]))

Q.4: [2, 3, 4]


In [12]:
# Q.5 - List Manipulation - Get First N Elements
# Returns only the first n elements using slicing
def get_first_n(lst, n):
    """
    Returns the first n elements of a list.

    Parameters:
        lst (list): Input list
        n (int): Number of elements to return from the start

    Returns:
        list: First n elements
    """
    return lst[:n]

print("Q.5:", get_first_n([1, 2, 3, 4, 5], 3))

Q.5: [1, 2, 3]


In [13]:
# Q.6 - List Manipulation - Extract Last N Elements
# Uses negative slicing to grab elements from the end
def get_last_n(lst, n):
    """
    Returns the last n elements of a list.

    Parameters:
        lst (list): Input list
        n (int): Number of elements to return from the end

    Returns:
        list: Last n elements
    """
    return lst[-n:]

print("Q.6:", get_last_n([1, 2, 3, 4, 5], 2))

Q.6: [4, 5]


In [14]:
# Q.7 - List Manipulation - Reverse Skip
# Starts from second-to-last element, goes backward, skips one each time
def reverse_skip(lst):
    """
    Returns every second element starting from second-to-last, moving backward.

    Parameters:
        lst (list): Input list

    Returns:
        list: Every second element in reverse order
    """
    return lst[-2::-2]

print("Q.7:", reverse_skip([1, 2, 3, 4, 5, 6]))

Q.7: [5, 3, 1]


In [15]:
# SECTION: Nested Lists (Q.1 to Q.8)
# Q.1 - Nested Lists - Flatten a Nested List
# Converts [[1,2],[3,4],[5]] into [1,2,3,4,5]
def flatten(lst):
    """
    Flattens a nested list into a single list.

    Parameters:
        lst (list): A nested list

    Returns:
        list: A single flattened list
    """
    result = []
    for sublist in lst:
        for item in sublist:
            result.append(item)
    return result

print("Q.1:", flatten([[1, 2], [3, 4], [5]]))

Q.1: [1, 2, 3, 4, 5]


In [18]:
# Q.2 - Nested Lists - Access a Nested Element
# Uses a list of indices to dig into a nested list
def access_nested_element(lst, indices):
    """
    Accesses a specific element in a nested list using indices.

    Parameters:
        lst (list): A nested list
        indices (list): List of indices to navigate to the element

    Returns:
        The element at the specified position
    """
    result = lst
    for i in indices:
        result = result[i]
    return result

print("Q.2:", access_nested_element([[1,2,3],[4,5,6],[7,8,9]], [1, 2]))

Q.2: 6


In [19]:
# Q.3 - Nested Lists - Sum of All Elements
# Recursively adds all numbers regardless of how deep they are nested
def sum_nested(lst):
    """
    Calculates the sum of all elements in a nested list.

    Parameters:
        lst (list): A nested list of numbers

    Returns:
        float: Sum of all elements
    """
    total = 0
    for item in lst:
        if isinstance(item, list):  # if item is itself a list, go deeper
            total += sum_nested(item)
        else:
            total += item
    return total

print("Q.3:", sum_nested([[1, 2], [3, [4, 5]], 6]))

Q.3: 21


In [20]:
# Q.4 - Nested Lists - Remove a Specific Element
# Goes through each sublist and removes all occurrences of elem
def remove_element(lst, elem):
    """
    Removes all occurrences of a specific element from a nested list.

    Parameters:
        lst (list): A nested list
        elem: The element to remove

    Returns:
        list: Nested list with the element removed
    """
    result = []
    for sublist in lst:
        result.append([item for item in sublist if item != elem])
    return result

print("Q.4:", remove_element([[1, 2], [3, 2], [4, 5]], 2))

Q.4: [[1], [3], [4, 5]]


In [21]:
# Q.5 - Nested Lists - Find Maximum Element
# Recursively searches through all levels to find the biggest number
def find_max(lst):
    """
    Finds the maximum element in a nested list.

    Parameters:
        lst (list): A nested list of numbers

    Returns:
        float: The maximum value found
    """
    max_val = None
    for item in lst:
        if isinstance(item, list):  # if item is a list, go deeper
            candidate = find_max(item)
        else:
            candidate = item
        if max_val is None or candidate > max_val:
            max_val = candidate
    return max_val

print("Q.5:", find_max([[1, 2], [3, [4, 5]], 6]))

Q.5: 6


In [22]:
# Q.6 - Nested Lists - Count Occurrences of an Element
# Counts how many times elem appears across all sublists
def count_occurrences(lst, elem):
    """
    Counts how many times an element appears in a nested list.

    Parameters:
        lst (list): A nested list
        elem: The element to count

    Returns:
        int: Number of times elem appears
    """
    count = 0
    for sublist in lst:
        for item in sublist:
            if item == elem:
                count += 1
    return count

print("Q.6:", count_occurrences([[1, 2], [2, 3], [2, 4]], 2))

Q.6: 3


In [23]:
# Q.7 - Nested Lists - Deep Flatten (any depth)
# Like Q.1 but works no matter how deeply nested the list is
def deep_flatten(lst):
    """
    Flattens a deeply nested list into a single list regardless of depth.

    Parameters:
        lst (list): A deeply nested list

    Returns:
        list: A completely flattened single list
    """
    result = []
    for item in lst:
        if isinstance(item, list):  # if item is still a list, go deeper
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

print("Q.7:", deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))

Q.7: [1, 2, 3, 4, 5, 6, 7, 8]


In [24]:
# Q.8 - Nested Lists - Average of All Elements
# Reuses deep_flatten to get all numbers, then calculates average
def average_nested(lst):
    """
    Calculates the average of all elements in a nested list.

    Parameters:
        lst (list): A nested list of numbers

    Returns:
        float: The average of all elements
    """
    all_elements = deep_flatten(lst)
    return sum(all_elements) / len(all_elements)

print("Q.8:", average_nested([[1, 2], [3, 4], [5, 6]]))

Q.8: 3.5


In [25]:
# SECTION: NumPy - Problem 1 - Array Creation
import numpy as np


# Q.1 - NumPy Array Creation - Initialize an Empty Array (2x2)
# np.empty creates array with random garbage values (uninitialized)
empty_arr = np.empty((2, 2))
print("Q.1 - Empty 2x2 array:\n", empty_arr)


Q.1 - Empty 2x2 array:
 [[4.03991404e-315 0.00000000e+000]
 [4.04466896e-315 4.04466896e-315]]


In [26]:
# Q.2 - NumPy Array Creation - Initialize an All Ones Array (4x2)
# np.ones fills every element with 1
ones_arr = np.ones((4, 2))
print("\nQ.2 - Ones 4x2 array:\n", ones_arr)


Q.2 - Ones 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [27]:
# Q.3 - NumPy Array Creation - Array Filled with a Specific Value
# np.full fills every element with the value you choose
filled_arr = np.full((3, 3), 7)   # 3x3 array filled with 7
print("\nQ.3 - Array filled with 7:\n", filled_arr)


Q.3 - Array filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [28]:
# Q.4 - NumPy Array Creation - Zeros with Same Shape as Existing Array
# np.zeros_like copies the shape but fills everything with 0
existing = np.ones((3, 4))         # our existing array
zeros_like_arr = np.zeros_like(existing)
print("\nQ.4 - Zeros like existing array:\n", zeros_like_arr)



Q.4 - Zeros like existing array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [29]:
# Q.5 - NumPy Array Creation - Ones with Same Shape as Existing Array
# np.ones_like copies the shape but fills everything with 1
ones_like_arr = np.ones_like(existing)
print("\nQ.5 - Ones like existing array:\n", ones_like_arr)


Q.5 - Ones like existing array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [30]:
# Q.6 - NumPy Array Creation - Convert a List to NumPy Array
# np.array() converts a regular Python list into a NumPy array
new_list = [1, 2, 3, 4]
numpy_arr = np.array(new_list)
print("\nQ.6 - Converted list to NumPy array:", numpy_arr)
print("      Type:", type(numpy_arr))


Q.6 - Converted list to NumPy array: [1 2 3 4]
      Type: <class 'numpy.ndarray'>


In [31]:
# SECTION: NumPy - Problem 2 - Array Manipulation
import numpy as np


# Q.1 - Array Manipulation - Values Ranging from 10 to 49
# np.arange works like range() but returns a numpy array
arr1 = np.arange(10, 50)
print("Q.1 - Array from 10 to 49:\n", arr1)

Q.1 - Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [32]:
# Q.2 - Array Manipulation - 3x3 Matrix with Values 0 to 8
# np.arange(9) gives [0,1,2,3,4,5,6,7,8] then reshape makes it 3x3
arr2 = np.arange(9).reshape(3, 3)
print("\nQ.2 - 3x3 matrix (0 to 8):\n", arr2)



Q.2 - 3x3 matrix (0 to 8):
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [33]:
# Q.3 - Array Manipulation - 3x3 Identity Matrix
# np.eye creates a matrix with 1s on the diagonal and 0s everywhere else
arr3 = np.eye(3)
print("\nQ.3 - 3x3 Identity matrix:\n", arr3)


Q.3 - 3x3 Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [34]:
# Q.4 - Array Manipulation - Random Array of Size 30 and its Mean
# np.random.random() creates random numbers between 0 and 1
arr4 = np.random.random(30)
print("\nQ.4 - Random array of size 30:\n", arr4)
print("      Mean:", arr4.mean())



Q.4 - Random array of size 30:
 [0.09423926 0.75123953 0.59255883 0.16498941 0.49062223 0.46681636
 0.13981356 0.44780106 0.37059057 0.28641448 0.6214281  0.48911296
 0.60802358 0.54054668 0.97851466 0.35003953 0.66321176 0.14200873
 0.66290508 0.1246102  0.40526235 0.61770761 0.71535496 0.39493866
 0.57143796 0.47334473 0.36602625 0.02102966 0.32901772 0.81906581]
      Mean: 0.45662241052867963


In [35]:
# Q.5 - Array Manipulation - 10x10 Random Array, Min and Max
# np.random.random((10,10)) creates a 10x10 grid of random numbers
arr5 = np.random.random((10, 10))
print("\nQ.5 - 10x10 random array:\n", arr5)
print("      Minimum value:", arr5.min())
print("      Maximum value:", arr5.max())



Q.5 - 10x10 random array:
 [[0.14264037 0.09347042 0.25456183 0.81341189 0.62965508 0.44449426
  0.23112787 0.30179588 0.23400025 0.2726361 ]
 [0.47470568 0.4621591  0.5261744  0.21005154 0.47577995 0.03514886
  0.0824122  0.00819465 0.15604742 0.88389334]
 [0.57437693 0.18387429 0.54848063 0.39244562 0.9051558  0.47812263
  0.8086495  0.81029133 0.06854385 0.85795667]
 [0.48331859 0.16975803 0.63390889 0.8752089  0.98745782 0.78487608
  0.38007912 0.1784732  0.77040252 0.67376246]
 [0.0586489  0.62630779 0.17442936 0.93813854 0.65523439 0.22340992
  0.32391105 0.31825821 0.22747195 0.64983254]
 [0.0363844  0.68630768 0.87439746 0.1956016  0.98209184 0.52831099
  0.96879247 0.45356328 0.07205868 0.61853827]
 [0.31948587 0.14804501 0.54249516 0.38391545 0.1845291  0.42064241
  0.68240047 0.24127254 0.68211017 0.94154946]
 [0.97695459 0.18066597 0.06167618 0.4652138  0.7939831  0.55615613
  0.83935578 0.75156458 0.51032633 0.84647337]
 [0.77771051 0.73789447 0.16604733 0.51887656 0.2002

In [36]:
# Q.6 - Array Manipulation - Zero Array of Size 10, Replace 5th Element with 1
# Remember: index starts at 0, so 5th element is at index 4
arr6 = np.zeros(10)
arr6[4] = 1
print("\nQ.6 - Zero array with 5th element replaced by 1:\n", arr6)


Q.6 - Zero array with 5th element replaced by 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [37]:
# Q.7 - Array Manipulation - Reverse an Array
# [::-1] is the slicing trick to reverse, same as we did in list manipulation!
arr7 = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr7[::-1]
print("\nQ.7 - Reversed array:\n", reversed_arr)


Q.7 - Reversed array:
 [0 4 0 0 2 1]


In [38]:
# Q.8 - Array Manipulation - 2D Array with 1 on Border and 0 Inside
# np.ones creates all 1s, then we set everything except the border to 0
arr8 = np.ones((5, 5))
arr8[1:-1, 1:-1] = 0        # everything inside the border becomes 0
print("\nQ.8 - 2D array with 1 on border and 0 inside:\n", arr8)


Q.8 - 2D array with 1 on border and 0 inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [39]:
# Q.9 - Array Manipulation - 8x8 Checkerboard Pattern
# np.zeros creates all 0s, then we fill alternating positions with 1
# [1::2, ::2]  = odd rows, even columns  → 1
# [::2, 1::2]  = even rows, odd columns  → 1
arr9 = np.zeros((8, 8), dtype=int)
arr9[1::2, ::2] = 1
arr9[::2, 1::2] = 1
print("\nQ.9 - 8x8 Checkerboard pattern:\n", arr9)


Q.9 - 8x8 Checkerboard pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [40]:
# SECTION: NumPy - Problem 4 - Matrix Operations
import numpy as np

# Given arrays (do not change these!)
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])


# -----------------------------------------------


# Q.1 - Matrix Operations - Prove A × A_inverse = Identity Matrix
# np.linalg.inv() gives the inverse of a matrix
# When you multiply a matrix by its inverse you always get identity matrix
A_inv = np.linalg.inv(A)
result1 = np.dot(A, A_inv)
print("Q.1 - A × A_inverse (should be Identity matrix):")
print(np.round(result1))          # np.round cleans up tiny decimal errors

Q.1 - A × A_inverse (should be Identity matrix):
[[1. 0.]
 [0. 1.]]


In [41]:
# Q.2 - Matrix Operations - Prove AB is NOT equal to BA
# Matrix multiplication is not commutative!
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nQ.2 - AB:\n", AB)
print("      BA:\n", BA)
print("      AB == BA?", np.array_equal(AB, BA))    # should print False


Q.2 - AB:
 [[23 13]
 [51 29]]
      BA:
 [[36 44]
 [13 16]]
      AB == BA? False


In [42]:
# Q.3 - Matrix Operations - Prove (AB)^T = B^T × A^T
# .T gives the transpose of a matrix (flips rows and columns)
AB_transpose = np.dot(A, B).T
BT_AT = np.dot(B.T, A.T)
print("\nQ.3 - (AB)^T:\n", AB_transpose)
print("      B^T × A^T:\n", BT_AT)
print("      Are they equal?", np.array_equal(AB_transpose, BT_AT))


Q.3 - (AB)^T:
 [[23 51]
 [13 29]]
      B^T × A^T:
 [[23 51]
 [13 29]]
      Are they equal? True


In [43]:
# Q.4 - Matrix Operations - Solve System of Linear Equations
# The equations are:
#  2x - 3y +  z = -1
#   x -  y + 2z = -3
#  3x +  y -  z =  9
#
# We write this as AX = B where:
# A = coefficient matrix, X = [x,y,z], B = result matrix

# Step 1: Write the equations as matrices
A_eq = np.array([[2, -3,  1],
                 [1, -1,  2],
                 [3,  1, -1]])

B_eq = np.array([-1, -3, 9])

# Step 2: Solve using inverse method  X = A_inverse × B
A_eq_inv = np.linalg.inv(A_eq)
X = np.dot(A_eq_inv, B_eq)
print("\nQ.4 - Solution using Inverse Method:")
print(f"      x = {round(X[0])}")
print(f"      y = {round(X[1])}")
print(f"      z = {round(X[2])}")



Q.4 - Solution using Inverse Method:
      x = 2
      y = 1
      z = -2


In [44]:
# Q.5 - Matrix Operations - Solve Same Equations using np.linalg.solve
# np.linalg.solve is cleaner and more accurate than inverse method
X2 = np.linalg.solve(A_eq, B_eq)
print("\nQ.5 - Solution using np.linalg.solve:")
print(f"      x = {round(X2[0])}")
print(f"      y = {round(X2[1])}")
print(f"      z = {round(X2[2])}")


Q.5 - Solution using np.linalg.solve:
      x = 2
      y = 1
      z = -2


In [45]:
# SECTION: NumPy - Speed Experiment
import numpy as np
import time
# Q.1 - Speed Experiment - Element-wise Addition
# Adding two lists/arrays of 1,000,000 elements

size = 1_000_000

a_list = list(range(size))
b_list = list(range(size))
a_np = np.array(a_list)
b_np = np.array(b_list)

# Using Python List
start = time.time()
result = [a_list[i] + b_list[i] for i in range(size)]
end = time.time()
print("Q.1 - Element-wise Addition:")
print(f"      Python List time : {end - start:.5f} seconds")

# Using NumPy
start = time.time()
result = a_np + b_np
end = time.time()
print(f"      NumPy Array time : {end - start:.5f} seconds")

Q.1 - Element-wise Addition:
      Python List time : 0.23197 seconds
      NumPy Array time : 0.03028 seconds


In [46]:
# Q.2 - Speed Experiment - Element-wise Multiplication
# Multiplying two lists/arrays of 1,000,000 elements

# Using Python List
start = time.time()
result = [a_list[i] * b_list[i] for i in range(size)]
end = time.time()
print("\nQ.2 - Element-wise Multiplication:")
print(f"      Python List time : {end - start:.5f} seconds")

# Using NumPy
start = time.time()
result = a_np * b_np
end = time.time()
print(f"      NumPy Array time : {end - start:.5f} seconds")


Q.2 - Element-wise Multiplication:
      Python List time : 0.12112 seconds
      NumPy Array time : 0.01681 seconds


In [47]:
# Q.3 - Speed Experiment - Dot Product
# Computing dot product of two lists/arrays of 1,000,000 elements

# Using Python List
start = time.time()
result = sum(a_list[i] * b_list[i] for i in range(size))
end = time.time()
print("\nQ.3 - Dot Product:")
print(f"      Python List time : {end - start:.5f} seconds")

# Using NumPy
start = time.time()
result = np.dot(a_np, b_np)
end = time.time()
print(f"      NumPy Array time : {end - start:.5f} seconds")


Q.3 - Dot Product:
      Python List time : 0.10906 seconds
      NumPy Array time : 0.00202 seconds


In [48]:
# Q.4 - Speed Experiment - Matrix Multiplication
# Multiplying two 1000x1000 matrices

size_matrix = 1000

a_mat_list = [[1] * size_matrix for _ in range(size_matrix)]
b_mat_list = [[1] * size_matrix for _ in range(size_matrix)]
a_mat_np = np.ones((size_matrix, size_matrix))
b_mat_np = np.ones((size_matrix, size_matrix))

# Using Python List
start = time.time()
result = [[sum(a_mat_list[i][k] * b_mat_list[k][j]
          for k in range(size_matrix))
          for j in range(size_matrix)]
          for i in range(size_matrix)]
end = time.time()
print("\nQ.4 - Matrix Multiplication (1000x1000):")
print(f"      Python List time : {end - start:.5f} seconds")
# Using NumPy
start = time.time()
result = np.dot(a_mat_np, b_mat_np)
end = time.time()
print(f"      NumPy Array time : {end - start:.5f} seconds")


Q.4 - Matrix Multiplication (1000x1000):
      Python List time : 115.54991 seconds
      NumPy Array time : 0.09220 seconds
